export const encouragements = [
	"So proud of you!",
	"Now you have it",
	"You made it happen",
	"You are learning fast",
	"That's the best ever",
	"You're on a roll!",
	"Keep up the good work",
	"You've got the hang of it",
	"Glad that you stuck with it",
	"That's quite an improvement",
	"It's a joy to work with you",
	"That's some real progress!",
	"You really make this fun!",
	"There's no stopping you",
	"You make it look easy",
	"Now that's what I call a great answer!",
	"I see where you're coming from",
	"You did that really well",
	"You must have been practicing",
	"You're really learning a lot",
	"That's coming along nicely",
	"I'm happy to see you working like that",
	"That's the way to do it",
	"I'm proud of the way you worked today",
	"You've just about got it",
	"What a nice ideal",
	"That's the best you've ever done",
	"Just keep doing your best",
	"I knew you could do it",
	"You are doing that much better today",
	"Keep working on it, you're getting better",
	"Couldn't have done it better myself",
	"That's the right way to do it",
	"One more time and you'll have it",
	"You're getting better all the time",
	"You did it that time!",
	"Now you've figured it out",
	"You've just about mastered that",
	"That's better than ever",
	"You did a lot of work today!",
	"i'd never bet against you!",
	"You certainly did well today",
	"You outdid yourself today",
	"I've never seen anyone do it better",
	"I think you've got it now",
	"You sure figured that out",
	"It's such a pleasure to watch you grow",
	"That makes me feel good",
	"You're on the right track now",
	"You're really working hard today",
	"Beautiful",
	"Yes!",
	"Unbelievable!",
	"Much better",
	"Top notch!",
	"Terrific idea!",
	"Pure genius!",
	"First class!",
	"Well said.",
	"Great teamwork!",
	"Wonderful work!",
	"Good going!",
	"Excellent effort!",
	"You're right!",
	"That's right!",
	"Getting better!",
	"Huge improvement!",
	"Quite impressive!",
	"That's it.",
	"You got it!",
	"Way to go!",
	"Love that answer!",
	"Good for you!",
	"That's the way!",
	"Nice going.",
	"Good thinking!",
	"You remembered.",
	"I'm impressed!",
	"You just did it!",
	"Love that attitude!",
	"Way to go.",
	"Keep it up!",
	"I like that.",
	"Love that focus!",
	"That's really nice.",
	"Way to go.",
	"You're doing fine.",
	"Keep on trying!",
	"You're catching on.",
	"Good for you!",
	"That's the way!",
	"You're amazing!",
	"That was hard work.",
	"Glad you shared that.",
	"You're almost there.",
	"Well, look at you!",
	"You figured it out!",
	"I knew you could do it.",
	"That's quite an improvement.",
	"Now you've figured it out!",
	"You made my day!",
];
